version: '3.7'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: project_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data
    container_name: coordinate_db
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./migrations/v1.0.0.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5432
    ports:
      - "5432:5432"
    restart: always
  backend:
    image: backend
    build: &build_backend
      context: .
      dockerfile: Dockerfile
    volumes: &volumes
      - .:/app
    environment:
      CONFIG_PATH: config/config.yaml
    container_name: coordinate_backend
    command: python3.9 main.py
    ports:
      - "8080:8080"
    depends_on:
      - database
  database-pytest:
    image: postgres:latest
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: main
    container_name: coordinate_db_test
    command: -p 5433
    ports:
      - "5433:5433"
    volumes:
     - ./migrations/v1.0.0.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    profiles: ["test"]
  tests:
    build: &build_test_backend
      context: .
      dockerfile: test.Dockerfile
    volumes: *volumes
    environment:
      ROSETTA_CONFIG_PATH: config/pytest.yaml
    container_name: coordinate_tests
    command: pytest -svvx tests
    depends_on:
      - database-pytest
    profiles: ["test"]
  flake:
    build: *build_test_backend
    command: flake8 --config=.flake8 .
    volumes: &volumes_read_only
      - type: bind
        source: .
        target: /app
        read_only: True
    container_name: coordinate_flake8
    profiles: ["lints"]
  mypy:
    build: *build_test_backend
    command: mypy --ignore-missing-imports api bl dl main.py config.py
    volumes: *volumes_read_only
    container_name: coordinate_mypy
    profiles: ["lints"]


volumes:
    database-data:
networks:
  default:
    name: coordinate-default
