name: release
on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true # Will only build if this is not here
        tags: ghcr.io/OWNER/IMAGE_NAME:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
        
    
